### ISSUE TITLE
Compiling under Mono breaks stuff

### ISSUE THREAD

**Issue by pogzie** [basho/riak-dotnet-client#298]
Following the guide on the documentation, doing a `make` after pulling the repo with the dependencies causes a problem regarding Zip with the message `Not registered task Zip.` I tried getting zip installed on my machine but still getting that error. Only workaround I found by tracing the cause is commenting out a section in `src/RiakClient/RiakClient.csproj` particularly 

```
    <!-- <ItemGroup>
      <ZipFiles Include="$(OutputPath)*.dll" />
      <ZipFiles Include="$(OutputPath)*.xml" />
      <ZipFiles Include="$(OutputPath)*.pdb" />
    </ItemGroup>
    <Zip Files="@(ZipFiles)" WorkingDirectory="$(OutputPath)" ZipFileName="$(OutputPath)$(AssemblyName)-$(VersionString).zip" ZipLevel="9" /> -->
```

I dont know up to what extent this would affect running the Riak .Net client since I have zero knowledge in running .Net via mono (just following the guides)

**Comment by lukebakken** [comment]
What version of Mono are you using? Thanks.
