### ISSUE TITLE
RiakClient.Delete Bug

### ISSUE THREAD

**Issue by InfoTrendsGit** [basho/riak-dotnet-client#300]
RiakClient.Delete command doesn't work. 

My version is 2.0.0.0, which I downloaded a month ago and the last updated on GibHub was 4 months ago so my version is latest. 

Please help

**Comment by alexmoore** [comment]
What version of Riak are you running against?
What do you mean by "doesn't work"?   Do you have any sample code that shows the issue?

Thanks.

**Comment by InfoTrendsGit** [comment]
Hi, my cluster is currently running Riak 2.1.1.
I am able to use RiakClient.Search(), RiakClient.Get(), RiakClient.Put() but fail to get RiakClient.Delete() to work.

Here is the sample code

string bucketType = "InfoT";
string bucketName = "Users";
List<string> keys = new List<string> { "12345667", "12345678" };
List<RiakObjectId> riakIds = keys.Select(k => new RiakClient.Models.RiakObjectId(bucketType, bucketName, k)).ToList();

RiakClusterConfiguration clusterConfig = RiakClusterConfiguration.LoadFromConfig("myConfig");
RiakCluster cluster = new RiakCluster(clusterConfig, new RiakConnectionFactory());
RiakClient riakClient = cluster.CreateClient();
riakClient.Delete(riakIds); /* Doesn't work */

* I also tried to delete using single key instead of a list of keys and still doesn't work.

Please help

Thanks

**Comment by lukebakken** [comment]
Hello -

Can you please be more specific about "doesn't work"? Does the object remain in Riak, and/or do you get an error at that point? If the object remains in Riak, can you fetch the object using `curl -vvv` and provide both the command you use to fetch the object as well as the output from `curl`?

**Comment by InfoTrendsGit** [comment]
After issuing RiakClient.Delete() request to Riak, the objects are still the Riak. I gave it sometimes and check it again, still there. So alternatively I have to issue RestRequest (using RestSharp) to Riak, it remove the objects.

Before I used CorrugatedIron and it works. Then CorrugatedIron change its name RestClient, so I downloaded the new one, it no longer works. Codes are all the same, just different namespace. Do you think protobuf-net has something to do with it?

I am currently using protobuf-net v2.0.0.668 (which comes with RiakClient project)

**Comment by lukebakken** [comment]
I can't reproduce this issue, and you can see [in the integration test suite](https://github.com/basho/riak-dotnet-client/blob/develop/src/RiakClientTests.Live/GeneralIntegrationTests.cs#L310-L345) that `Delete` is tested. I just re-ran that test locally and it succeeded.

Could you please follow my instructions and fetch the object using HTTP and `curl` *after* you try and delete it? Here is an example command:

```sh
curl -4vvv http://RIAK_HOST:8098/types/InfoT/buckets/Users/keys/12345678
```

Replace `RIAK_HOST` with the DNS name or IP address of one of your Riak servers, or use `localhost` if you execute `curl` on the same server as one of your Riak nodes.
