### ISSUE TITLE
Riak client does not support the use of a load balancer

### ISSUE THREAD

**Issue by rob-somerville** [basho/riak-dotnet-client#306]
We are using a load balancer (an F5) in our environment to proxy requests to the Riak servers. Our configuration looks like this:

```xml
<riakConfig nodePollTime="5000" defaultRetryWaitTime="200" defaultRetryCount="3">
  <nodes>
    <node name="dev1" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
  </nodes>
</riakConfig>
```

The load balancer sits in front of 5 Riak servers. Under normal operation this works correctly. However, when we stop one of the Riak nodes, clients that have a connection to that server mark the node 'dev1' as 'inactive'. Since this is the only node available, further calls result in an error of "Cluster Unavailable" being returned. This error continues until the background polling thread detects that a connection can be made, which can take up to 5 seconds.

We have also tried setting the configuration like this:

```xml
<riakConfig nodePollTime="5000" defaultRetryWaitTime="200" defaultRetryCount="3">
  <nodes>
    <node name="dev1" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
    <node name="dev2" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
    <node name="dev3" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
    <node name="dev4" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
    <node name="dev5" hostAddress="RIAK-LB" pbcPort="8087" poolSize="10" />
  </nodes>
</riakConfig>
```

In this case we'll only get the cluster unavailable if all 5 nodes are connected to the same physical machine. Since our load balancer uses a round robin this is unlikely, but it's not guaranteed to work because requests from other clients on the network also hit the load balancer.

**Comment by lukebakken** [comment]
@rob-somerville you already tried the usual workaround. Thanks for the PR, I'll check it out.

**Comment by lukebakken** [comment]
Hi @rob-somerville -

I pushed a new beta release:

**Comment by rob-somerville** [comment]
Thanks Luke,

We’ll pull it down and give it a try.

Thanks again.

Rob

**Comment by lukebakken** [comment]
Hi @rob-somerville, any news from testing?

**Comment by rob-somerville** [comment]
Hey Luke,

So far it’s looking good. Tested with the load balancer and that looked good. More testing going on today and tomorrow as we integrate the beta into our latest code.

Thanks,

Rob

**Comment by rob-somerville** [comment]
Hi Luke,

We finished up the last of our regression tests with the Beta client. We didn’t find any issues – looks good.

Thanks,

Rob

**Comment by lukebakken** [comment]
Thank you for the update. I'll get the final release out this week.

**Comment by rob-somerville** [comment]
Hey Luke,

Just checking in. Any update on the release?

Thanks,

Rob

**Comment by lukebakken** [comment]
@rob-somerville - I have been swamped with other work, but will get to this today or tomorrow. Thanks for reminding me.

**Comment by lukebakken** [comment]
@rob-somerville I am releasing `2.3.0-beta3` right now. It moves the `externalLoadBalancer` setting to the node configuration, from the cluster one. There are cases when people use multiple load balancers. My testing passes, if you could try it out I will get the final release out when I hear back. Thanks!!!

**Comment by rob-somerville** [comment]
Hey Luke,

We’ve updated our configs and verified. Looks good.

Thanks,

Rob

**Comment by lukebakken** [comment]
Awesome! Official release on its way.

**Comment by lukebakken** [comment]
@rob-somerville - you're all set. Thank you for your patience and willingness to test.

https://www.nuget.org/packages/RiakClient/

**Comment by rob-somerville** [comment]
Thanks Luke, appreciate it.
