### ISSUE TITLE
RiakClient.Delete issue [JIRA: CLIENTS-898]

### ISSUE THREAD

**Issue by alexmoore** [basho/riak-dotnet-client#310]
_From @InfoTrendsGit on June 19, 2016 15:54_

Cannot delete if using RiakClient.Delete(IEnumerable<RiakObjectId> riakObjectIds)

But Delete works fine if using RiakClient.Delete(RiakObjectId riakObjectIds)

_Copied from original issue: basho/riak-java-client#630_

**Comment by alexmoore** [comment]
Hi, could you provide the following information?

- [ ] Riak Java Client version
- [ ] Java version
- [ ] Riak version
- [ ] Operating System / Distribution & Version
- [ ] Riak `error.log` file, if applicable
- [ ] Sample data, if applicable

**Comment by alexmoore** [comment]
_From @InfoTrendsGit on June 20, 2016 15:5_

Sorry. Yes, it is .NET RiakClient. It does work if deleting a "collection of RiakObjectId". But it does work if delete individual RiakObjectId

**Comment by lukebakken** [comment]
Also see #300

**Comment by lukebakken** [comment]
Please provide the requested information from issue #300.
