### ISSUE TITLE
Fluent connection configuration ?

### ISSUE THREAD

**Issue by cemremengu** [basho/riak-dotnet-client#331]
Is there any `fluent` way of configuring a riak connection besides reading from a config file ?

Or at least from the new `appsettings.json` config file ?

It would be very useful if there was one of these.

**Comment by lukebakken** [comment]
You can pass any class that implements `IRiakClusterConfiguration` to the `RiakCluster` constructor:

https://github.com/basho/riak-dotnet-client/blob/develop/src/RiakClient/RiakCluster.cs#L58

Obviously, it's not a fluent interface but it is what is provided. You can read `appsettings.json` and create instances of `RiakClusterConfiguration` and `RiakNodeConfiguration` as needed from that.

 A PR to implement a fluent interface would be most welcome, too.

**Comment by cemremengu** [comment]
I think adding a fluent interface will solve the #332 . It will be best to let users read the configuration from wherever and however they want instead of having a dependency on `System.configuration`.

I will come up with a PR when I have some time.
