### ISSUE TITLE
Add warning and safety mechanism to prevent unintentional list [buckets | keys] operations

### ISSUE THREAD

**Issue by DSomogyi** [basho/riak-dotnet-client#335]
Add warning and safety mechanism to prevent unintentional list [buckets | keys] operations.

**Comment by DSomogyi** [comment]
Updated

**Comment by DSomogyi** [comment]
Update

**Comment by DSomogyi** [comment]
Linked

**Comment by Basho-JIRA** [comment]
Are they linked?
 

***[posted via JIRA by Derek Somogyi]***
